workload_name: continuousrw_nocompact_2kvalues
patches:
  # Do not use the sharded tasks in this patch as they did not have the
  # implicit ECOC create workaround.
  63594ef1a4cf470f0052bbb4:
    linux-3-node-replSet-qebench:
    - "genny_qebench_continuousrw_nocompact"
  635985aad1fe07493271b66b:
    linux-shard-lite-qebench:
    - "genny_qebench_continuousrw_nocompact"
genny_metrics:
  tests:
  - "ContinuousRW.Crud"
  - "ContinuousRW.update"
  - "ContinuousRW.insert"
  - "ContinuousRW.find"
  metrics:
  - "OperationsTotal"
  - "DocumentsTotal"
  - "SizeTotal"
  - "DurationTotal"
  - "OverheadTotal"
  - "ErrorsTotal"
  - "AverageLatency"
  - "AverageSize"
  - "OperationThroughput"
  - "DocumentThroughput"
  - "SizeThroughput"
  - "LatencyMin"
  - "LatencyMax"
  - "Latency50thPercentile"
  - "Latency80thPercentile"
  - "Latency90thPercentile"
  - "Latency95thPercentile"
  - "Latency99thPercentile"
  - "WorkersMin"
  - "WorkersMax"
  - "ErrorRate"
curator: "/home/ubuntu/erwee/genny/build/curator/curator"
